common: &common
  working_directory: ~/repo

  docker:
    - image: unifio/ci:5.0.1005-ruby-2.5.5

  environment:
    AWS_REGION: 'us-east-1'

version: 2

jobs:
  build:
    <<: *common

    steps:
      - checkout

      - run:
          name: Verify
          environment:
            CI_REPORTS: 'reports'
            COVALENCE_TEST_ENVS: 'basic,complete'
          command: |
            mkdir reports
            bundle exec rake ci

      - store_test_results:
          path: reports

  basic:
    <<: *common

    steps:
      - checkout

      - run:
          name: Test DMZ only configuration
          command: bundle exec rake basic:no-lan:apply

      - run:
          name: Test defaults
          command: |
            bundle exec rake basic:defaults:apply
            bundle exec rake basic:defaults:destroy

      - run:
          name: Test some base module options and expand to 3 AZs
          command: |
            bundle exec rake basic:base-options:apply

      - run:
          name: Test VPN gateway attachment
          command: |
            bundle exec rake basic:vpg-attach:apply
            bundle exec rake basic:vpg-attach:destroy

      - run:
          name: Clean up
          when: always
          command: |
            bundle exec rake basic:destroy

  complete:
    <<: *common

    steps:
      - checkout

      - run:
          name: Test more options and overrides
          command: |
            bundle exec rake complete:overrides:apply || true
            # Need to run twice due to frequent timing issues
            # see https://github.com/unifio/terraform-aws-vpc/issues/39
            bundle exec rake complete:overrides:apply

      - run:
          name: Test peering connection
          command: |
            bundle exec rake complete:peer-vpc:apply || true
            # Need to run twice due to frequent timing issues
            # see https://github.com/unifio/terraform-aws-vpc/issues/39
            bundle exec rake complete:peer-vpc:apply
            bundle exec rake peering:peer-connect:apply

      - run:
          name: Clean up
          when: always
          command: |
            bundle exec rake peering:destroy || true
            bundle exec rake complete:destroy

workflows:
  version: 2

  vpc_module:
    jobs:
      - build
      - basic:
          requires:
            - build
      - complete:
          requires:
            - build
